"""Initial migrate

Revision ID: 5ddcc9ddc1dc
Revises: 
Create Date: 2025-11-07 15:22:40.763743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5ddcc9ddc1dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure PostGIS is available for geometry columns
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_activity_name_parent')
    )
    op.create_table('buildings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='chk_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='chk_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_table('organization_phones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_phones')
    op.drop_table('organization_activities')
    op.drop_table('organizations')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
