"""add indexes

Revision ID: 891af7e18832
Revises: 5ddcc9ddc1dc
Create Date: 2025-11-07 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891af7e18832'
down_revision: Union[str, Sequence[str], None] = '5ddcc9ddc1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Проверяем, существует ли индекс
    result = connection.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 
                FROM pg_indexes 
                WHERE indexname = 'idx_buildings_geom' 
                AND tablename = 'buildings'
            )
            """
        )
    )
    index_exists = result.scalar()
    
    # Создаем индекс только если он не существует
    if not index_exists:
        op.create_index(
            'idx_buildings_geom',
            'buildings',
            ['geom'],
            postgresql_using='gist'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Проверяем, существует ли индекс
    result = connection.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 
                FROM pg_indexes 
                WHERE indexname = 'idx_buildings_geom' 
                AND tablename = 'buildings'
            )
            """
        )
    )
    index_exists = result.scalar()
    
    # Удаляем индекс только если он существует
    if index_exists:
        op.drop_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist')
    # ### end Alembic commands ###

